user=SEU_USER_AQUI
password=SENHA_AQUI
dburl=jdbc:mysql://localhost:3306/hrproject
useSSL=false

# ATENÇÃO: Renomeie este arquivo para 'db.properties'
# e substitua as variaveis abaixo pelas credenciais do seu banco de dados local.